version: "3.7"

x-transformer-env: &transformer-env
  # Logging
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "console"

  # DB
  DB_DRIVER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "${DB_USER:-icon}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_DBNAME: "${NETWORK_NAME:-mainnet}_transformer_v2"
  DB_SSL_MODE: "disable"
  DB_TIMEZONE: "UTC"

services:
  transformer-missing:
    image: sudoblock/icon-transformer:latest
    restart: always
    environment:
      <<: *transformer-env
      FIND_MISSING_RUN_ONLY: "true"
      FIND_MISSING_EXTRACTOR_API_LOCATION: "http://claim-extractor:9876/api/v1"

#curl -X 'POST' \
#  'http://claim-extractor:9090/api/v1/create-job' \
#  -H 'accept: application/json' \
#  -H 'Content-Type: */*' \
#  -d '{
#  "end_block_number": 2,
#  "start_block_number": 1
#}'
